config/routes.rb
Rails.application.routes.draw do
  resources :locais
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'locais#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/local.rb
class Local < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locais_controller.rb
class LocaisController < ApplicationController
  before_action :set_local, only: %i[ show edit update destroy ]
  before_action :set_bairro_options, only: [:new, :create ,:edit, :update]

  # GET /locais or /locais.json
  def index
    @locais = Local.all
  end

  # GET /locais/1 or /locais/1.json
  def show
  end

  # GET /locais/new
  def new
    @local = Local.new
  end

  # GET /locais/1/edit
  def edit
  end

  # POST /locais or /locais.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to local_url(@local), notice: "Local was successfully created." }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locais/1 or /locais/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to local_url(@local), notice: "Local was successfully updated." }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locais/1 or /locais/1.json
  def destroy
    @local.destroy

    respond_to do |format|
      format.html { redirect_to locais_url, notice: "Local was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end


    def set_bairro_options
      @bairro_options = Local.all.pluck(:bairro, :id)
   end


    # Only allow a list of trusted parameters through.
    def local_params
      params.require(:local).permit(:bairro, :referencia, :logradouro, :numero, :rua)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    require 'net/http'
    require 'uri'
    require 'json'
    require 'geocoder'

    def send_request
        bairro = Local.last.bairro
        rua = Local.last.rua
        logradouro = Local.last.logradouro
        referencia = Local.last.referencia
        numero = Local.last.numero
        address = bairro + " " + "Parnamirim"
        localizacao = Geocoder.search(address)
        coordenadas = localizacao.first.coordinates
        lat = coordenadas[0].to_s 
        long = coordenadas[1].to_s
        uri = URI.parse("http://localhost:3007/api/v1/bairros/")
        header = {'Content-Type': 'application/json'}
        bairro = {nome_bairro: bairro, rua:rua, logradouro:logradouro, referencia:referencia, numero:numero, lat:lat, long:long}
        http = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Post.new(uri.request_uri, header)
        request.body = bairro.to_json
        puts request.body
        response = http.request(request)
        puts response
        puts lat
        puts long
        end

    def button_path
        out = ''
        out << link_to('Salvar Local', send_request, class: 'btn btn-primary')
        out.html_safe
    end 

end

app/helpers/locais_helper.rb
module LocaisHelper
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Light Web</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'dataturbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' =>
true %>
 <%= csrf_meta_tags %>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>

<div class="container rounded-corners">
<%= yield %>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>




</body>
</html>

app/views/locais/_form.html.erb
<%= form_with(model: local) do |form| %>
  <% if local.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
        <% local.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="form-group">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, class:"form-control", placeholder:"Próximo a..." %>
  </div>


  <div class="form-group">
    <%= form.label :rua %>
    <%= form.text_field :rua, class:"form-control", placeholder:"Rua..." %>
  </div>



 <div class="form-group">
    <%= form.label :referencia %>
    <%= form.text_field :referencia, class:"form-control", placeholder:"Próximo a..." %>
  </div>

   <div class="form-group">
    <%= form.label :logradouro %>
    <%= form.text_field :logradouro, class:"form-control", placeholder:"Insira um logradouro" %>
  </div>

<!---->
   <div class="form-group">
    <%= form.label :numero %>
    <%= form.text_field :numero, class:"form-control", placeholder:"Número da casa" %>
  </div>


  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary"  %>
  </div>
<% end %>

app/views/locais/_local.html.erb
<div id="<%= dom_id local %>">
  <p>
    <strong>Bairro:</strong>
    <%= local.bairro %>
  </p>

  <p>
    <strong>Referencia:</strong>
    <%= local.referencia %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= local.logradouro %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= local.numero %>
  </p>

</div>

app/views/locais/edit.html.erb
<h1>Editing local</h1>

<%= render "form", local: @local %>
<br>

<div>
  <%= link_to "Show this local", @local %> |
  <%= link_to "Voltar", locais_path, class: "btn-btn primary" %>
</div>

app/views/locais/index.html.erb
<% if notice.present? %>
 <div id="notice" class="alert alert-success" role="alert"><%=
notice %></div>
<% end %>

<h1>Locais</h1>
 <p>Nenhuma Registro de Local Encontrado</p>
 <div class="float-md-left">
 <%= link_to 'Novo Endereço', new_local_path, class: "btn btn-primary" %>
 </div>

app/views/locais/new.html.erb
<h1>Cadastrar Local</h1>

<%= render "form", local: @local %>

<br>

<div>
  <%= link_to "Voltar", locais_path %>
  
</div>

app/views/locais/show.html.erb
<p id="notice"><%= notice %></p>
<form>

  <div class="form-group">
    <%= text_field_tag nil, @local.bairro, class:"form-control", disabled: true %>
  </div>

   <div class="form-group">
    <%= text_field_tag nil, @local.referencia, class:"form-control", disabled: true %>
  </div>

  
  
</form>

<div>
  <%= link_to "Editar Local", edit_local_path(@local), class: "btn btn-warning" %> <span style = "color: #FCF545">|</span>
  <%= link_to "Voltar", locais_path, class: "btn btn-success" %> <span style = "color: #FCF545">|</span>
  <%= button_path%>
  <br>
  <br>

  <%= button_to "Destroy this local", @local, method: :delete, class: "btn btn-danger" %>
</div>